version: '3.8'

services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_DATABASE: rides
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    ports:
      - '5234:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=rides
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        GOOGLE_API_KEY: ${GOOGLE_API_KEY} # Passa a variável como argumento de build
    container_name: frontend
    ports:
      - '80:80'
    depends_on:
      - backend
