version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_DATABASE: rides
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
    ports:
      - '5234:3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql-volume:
    driver: local