# Base do Node.js
FROM node:18

# Diretório de trabalho no container
WORKDIR /api

# Copiar os arquivos necessários do contexto de build da raiz
COPY ../package*.json ./
COPY ../tsconfig.json ./
COPY ./api ./

# Instalar dependências
RUN npm install
RUN npx tsc

# Expor a porta do backend
EXPOSE 8080

# Comando para iniciar o servidor
CMD ["node", "src/index.js"]
